### ISSUE TITLE
sineMod 440 crashes both with GHCi and GHC --make

### ISSUE THREAD

**Issue by Ebmtranceboy** [HeinrichApfelmus/tomato-rubato#2]
I have a problem with GHCi, version 7.0.3 :
when I ctrl+C the infinite sineMod 440, I have a segmentation fault and GHCi crashes...

A segmentation fault occurs when I compile  the example too:

$ ./example
^CErreur de segmentation

$ uname -r
3.0.0-16-generic

$ cat /etc/lsb-release | tail -1
DISTRIB_DESCRIPTION="Ubuntu 11.10"

**Comment by danschrage** [comment]
The fix (eliminating the code that frees the context and device) causes a problem of its own: it means that each time withSpeakers is called, an orphan context/device is left over and not freed. This eventually causes OpenAL to run out of memory. I just submitted a pull request that solves the original #2 issue on Linux while still freeing the device and context so it doesn't create any other problems.
